// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyH3aotW4qjCBkbKDh49939eXfoPZf6PE',
    appId: '1:736144587607:web:4a50bb4b507050a78d9c12',
    messagingSenderId: '736144587607',
    projectId: 'userfirebase-487d1',
    authDomain: 'userfirebase-487d1.firebaseapp.com',
    storageBucket: 'userfirebase-487d1.appspot.com',
    measurementId: 'G-VZWBTT2W3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsvM276caSL3EPf3FgxUhDZbIz05ZpFCY',
    appId: '1:736144587607:android:f19d0efd132e8ffb8d9c12',
    messagingSenderId: '736144587607',
    projectId: 'userfirebase-487d1',
    storageBucket: 'userfirebase-487d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0ZDw5MCRvjmBKHxzOe5K4WYypSQLSXlk',
    appId: '1:736144587607:ios:b390fa644c4336548d9c12',
    messagingSenderId: '736144587607',
    projectId: 'userfirebase-487d1',
    storageBucket: 'userfirebase-487d1.appspot.com',
    iosBundleId: 'com.example.userfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0ZDw5MCRvjmBKHxzOe5K4WYypSQLSXlk',
    appId: '1:736144587607:ios:b390fa644c4336548d9c12',
    messagingSenderId: '736144587607',
    projectId: 'userfirebase-487d1',
    storageBucket: 'userfirebase-487d1.appspot.com',
    iosBundleId: 'com.example.userfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyH3aotW4qjCBkbKDh49939eXfoPZf6PE',
    appId: '1:736144587607:web:5892bc76908d08538d9c12',
    messagingSenderId: '736144587607',
    projectId: 'userfirebase-487d1',
    authDomain: 'userfirebase-487d1.firebaseapp.com',
    storageBucket: 'userfirebase-487d1.appspot.com',
    measurementId: 'G-H7WDV89JF8',
  );

}